name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Add sha to tracks.js
        run: |
          last_commit_sha=$(git rev-parse --short HEAD)
          sed -i "s/\.\/tracks\.js/\.\/tracks\.js\?_=$last_commit_sha/" index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
